create extension if not exists "pgcrypto";

-- =========================================
-- ROLES
-- =========================================
create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  created_at timestamptz not null default now()
);

insert into public.roles (id, name, description)
values
  (1, 'student', 'Default student user'),
  (2, 'admin', 'Administrator user')
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description;

select setval(
  pg_get_serial_sequence('public.roles', 'id'),
  greatest((select max(id) from public.roles), 1),
  true
);

-- =========================================
-- RANKS
-- =========================================
create table if not exists public.ranks (
  id bigint generated by default as identity primary key,
  name text not null unique,
  min_xp integer not null,
  max_xp integer,
  created_at timestamptz not null default now(),
  constraint ranks_xp_check check (
    min_xp >= 0
    and (max_xp is null or max_xp >= min_xp)
  )
);

insert into public.ranks (id, name, min_xp, max_xp)
values
  (1, 'Beginner', 0, 149),
  (2, 'Apprentice', 150, 499),
  (3, 'Specialist', 500, 999),
  (4, 'Expert', 1000, 1749),
  (5, 'Master', 1750, 2499),
  (6, 'Grandmaster', 2500, null)
on conflict (id) do update set
  name = excluded.name,
  min_xp = excluded.min_xp,
  max_xp = excluded.max_xp;

select setval(
  pg_get_serial_sequence('public.ranks', 'id'),
  greatest((select max(id) from public.ranks), 1),
  true
);

-- =========================================
-- PROFILES
-- =========================================
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  auth_id uuid,
  email text,
  first_name text,
  last_name text,
  display_name text,
  avatar_url text,
  metadata jsonb not null default '{}'::jsonb,
  role_id bigint not null default 1 references public.roles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_profiles_role_id on public.profiles(role_id);

-- =========================================
-- USER STATS
-- =========================================
create table if not exists public.user_stats (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  xp integer not null default 0,
  current_rank_id bigint references public.ranks(id),
  updated_at timestamptz not null default now(),
  constraint user_stats_xp_check check (xp >= 0)
);

create index if not exists idx_user_stats_xp on public.user_stats(xp desc);
create index if not exists idx_user_stats_current_rank_id
  on public.user_stats(current_rank_id);

-- =========================================
-- JOBS
-- =========================================
create table if not exists public.jobs (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  category text,
  company text,
  pay numeric,
  location text,
  slots integer not null default 1,
  reward_xp integer not null default 50,
  status text not null default 'open',
  deadline timestamptz,
  recommended_rank_id bigint references public.ranks(id),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint jobs_slots_check check (slots >= 0),
  constraint jobs_reward_xp_check check (reward_xp >= 0),
  constraint jobs_status_check check (status in ('open', 'closed'))
);

create index if not exists idx_jobs_status on public.jobs(status);
create index if not exists idx_jobs_recommended_rank_id
  on public.jobs(recommended_rank_id);
create index if not exists idx_jobs_category on public.jobs(category);
create index if not exists idx_jobs_created_at on public.jobs(created_at desc);

-- =========================================
-- JOB APPLICATIONS
-- =========================================
create table if not exists public.job_applications (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null references public.jobs(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending',
  xp_awarded boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint job_applications_unique unique (job_id, user_id),
  constraint job_applications_status_check check (
    status in ('pending', 'accepted', 'in_progress', 'completed', 'rejected')
  )
);

create index if not exists idx_job_applications_job_id
  on public.job_applications(job_id);
create index if not exists idx_job_applications_user_id
  on public.job_applications(user_id);
create index if not exists idx_job_applications_status
  on public.job_applications(status);

-- =========================================
-- PARTIES
-- =========================================
create table if not exists public.parties (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  leader_id uuid references public.profiles(id) on delete set null,
  category text,
  min_rank_id bigint references public.ranks(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_parties_min_rank_id on public.parties(min_rank_id);
create index if not exists idx_parties_leader_id on public.parties(leader_id);

-- =========================================
-- PARTY MEMBERS
-- =========================================
create table if not exists public.party_members (
  id bigint generated by default as identity primary key,
  party_id bigint not null references public.parties(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member',
  joined_at timestamptz not null default now(),
  constraint party_members_unique unique (party_id, user_id),
  constraint party_members_role_check check (role in ('leader', 'member'))
);

create index if not exists idx_party_members_party_id
  on public.party_members(party_id);
create index if not exists idx_party_members_user_id
  on public.party_members(user_id);

-- =========================================
-- UPDATED_AT TRIGGER
-- =========================================
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists trg_user_stats_updated_at on public.user_stats;
create trigger trg_user_stats_updated_at
before update on public.user_stats
for each row execute function public.set_updated_at();

drop trigger if exists trg_jobs_updated_at on public.jobs;
create trigger trg_jobs_updated_at
before update on public.jobs
for each row execute function public.set_updated_at();

drop trigger if exists trg_job_applications_updated_at on public.job_applications;
create trigger trg_job_applications_updated_at
before update on public.job_applications
for each row execute function public.set_updated_at();

drop trigger if exists trg_parties_updated_at on public.parties;
create trigger trg_parties_updated_at
before update on public.parties
for each row execute function public.set_updated_at();

-- =========================================
-- AUTO PROFILE CREATION
-- =========================================
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  default_rank_id bigint;
begin
  select id into default_rank_id
  from public.ranks
  where min_xp = 0
  order by id
  limit 1;

  insert into public.profiles (
    id,
    auth_id,
    email,
    display_name,
    avatar_url,
    role_id
  )
  values (
    new.id,
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    new.raw_user_meta_data->>'avatar_url',
    1
  )
  on conflict (id) do nothing;

  insert into public.user_stats (
    user_id,
    xp,
    current_rank_id
  )
  values (
    new.id,
    0,
    default_rank_id
  )
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- =========================================
-- RANK UPDATE TRIGGER
-- =========================================
create or replace function public.update_rank_from_xp()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  resolved_rank_id bigint;
begin
  select id into resolved_rank_id
  from public.ranks
  where new.xp >= min_xp
    and (max_xp is null or new.xp <= max_xp)
  order by min_xp desc
  limit 1;

  new.current_rank_id = resolved_rank_id;
  return new;
end;
$$;

drop trigger if exists trg_update_rank on public.user_stats;
create trigger trg_update_rank
before insert or update of xp on public.user_stats
for each row execute function public.update_rank_from_xp();

-- =========================================
-- AWARD XP ON COMPLETION
-- =========================================
create or replace function public.award_xp_on_completion()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  reward integer;
begin
  if new.status = 'completed'
    and old.status is distinct from 'completed'
    and old.xp_awarded = false
  then
    select reward_xp into reward
    from public.jobs
    where id = new.job_id;

    update public.user_stats
    set xp = xp + coalesce(reward, 0)
    where user_id = new.user_id;

    new.xp_awarded = true;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_award_xp_on_completion on public.job_applications;
create trigger trg_award_xp_on_completion
before update of status on public.job_applications
for each row execute function public.award_xp_on_completion();

-- =========================================
-- AUTO-ADD PARTY LEADER
-- =========================================
create or replace function public.add_party_leader_as_member()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.leader_id is not null then
    insert into public.party_members (party_id, user_id, role)
    values (new.id, new.leader_id, 'leader')
    on conflict (party_id, user_id) do update set role = 'leader';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_add_party_leader_as_member on public.parties;
create trigger trg_add_party_leader_as_member
after insert on public.parties
for each row execute function public.add_party_leader_as_member();
